esphome:
  name: sonoff-rf-bridge
  friendly_name: Sonoff RF Bridge

esp8266:
  # sonoff r2 v2.2
  board: esp8285

# Enable logging
logger:
  baud_rate: 0

# Enable over-the-air updates.
ota:
  safe_mode: true
  password: !secret ota_password
  
status_led:
  # see sonoff_r2v2.2_connector_pinouts_fv1.txt for pin information
  pin: GPIO13
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

 
uart:
  tx_pin: 1
  rx_pin: 3
  baud_rate: 19200
  
  debug:
  
  # FIXME: attempt at debugging by increasing
  #rx_buffer_size: 1024
  
# Enable Home Assistant API
api:
# FIXME: enable this once it is understood
#  encryption:
#    key: "************************"

  services:
    - service: send_rf_code
      variables:
        sync: int
        low: int
        high: int
        code: int
      then:
        - rf_bridge.send_code:
            sync: !lambda 'return sync;'
            low: !lambda 'return low;'
            high: !lambda 'return high;'
            code: !lambda 'return code;'
    - service: send_rf_code_raw
      variables:
        raw: string
      then:
        - rf_bridge.send_raw:
            raw: !lambda 'return raw;'
    - service: learn
      then:
        - rf_bridge.learn


rf_bridge:
  on_code_received:
    then:
    #  - homeassistant.event:
    #     event: esphome.rf_code_received
    #      data:
    #        sync: !lambda 'return format_hex(data.sync);'
    #        low: !lambda 'return format_hex(data.low);'
    #        high: !lambda 'return format_hex(data.high);'
    #        code: !lambda 'return format_hex(data.code);'
      - homeassistant.event:
          event: esphome.rf_code_received
          data:
            sync: !lambda 'return int(data.sync);'
            low: !lambda 'return int(data.low);'
            high: !lambda 'return int(data.high);'
            code: !lambda 'return int(data.code);'
  
  on_advanced_code_received:
    then:
      - homeassistant.event:
          event: esphome.rf_advanced_code_received
          data:
            length: !lambda 'return format_hex(data.length);'
            protocol: !lambda 'return format_hex(data.protocol);'
            code: !lambda 'return data.code;'


button:

  - platform: template
    name: Advanced sniffing start
    id: asstart
    on_press:
      then:
        - rf_bridge.start_advanced_sniffing

  - platform: template
    name: Advanced sniffing stop
    id: ASStop
    on_press:
      then:
        - rf_bridge.stop_advanced_sniffing    

  - platform: template
    name: Bucket sniffing start
    id: BSstart
    on_press:
      then:
        - rf_bridge.start_bucket_sniffing 


switch:
  - platform: template
    id: range
    name: "Stove range light"
    optimistic: true
    turn_on_action: 
      - rf_bridge.send_code:
          sync: 0x2F08
          low:  0x0162
          high: 0x04A4
          code: 0x00C301    
    turn_off_action: 
      - rf_bridge.send_code:
          sync: 0x2F23
          low:  0x0163
          high: 0x04A1
          code: 0x00C303